# name: Keep Render Servers Alive

# on:
#   schedule:
#     - cron: '0 0 * * *'   # every 24 hours (at midnight UTC)
#   workflow_dispatch:        # allows manual trigger

# jobs:
#   ping:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Ping SIH Backend
#         run: curl -I https://sih-backend-27v5.onrender.com/swagger/index.html

#       - name: Ping SIH NGO Backend
#         run: curl -I https://sih-ngo-backend.onrender.com/swagger/index.html

#       - name: Ping Soil API
#         run: curl -I https://soil-api-cre9.onrender.com
